CREATE TABLE USER(
    UID VARCHAR(20) NOT NULL PRIMARY KEY,
    UNAME VARCHAR(255) NOT NULL,
    UEMAIL VARCHAR(255) NOT NULL,
    UPASS VARCHAR(255) NOT NULL,
    CONTACT_NO VARCHAR(255) NOT NULL,
    ISADMIN BOOLEAN NOT NULL,
    ISCHECKER BOOLEAN NOT NULL,
);

CREATE TABLE UNITS(
    UNIT_NAME VARCHAR(255) NOT NULL PRIMARY KEY,
    ISACTIVE BOOLEAN NOT NULL,
);

CREATE TABLE CATEGORIES(
    CAT_NAME VARCHAR(255) NOT NULL PRIMARY KEY,
    ISACTIVE BOOLEAN NOT NULL,
);

CREATE TABLE INVENTORY(
    IID VARCHAR(20) NOT NULL PRIMARY KEY ,
    VENDOR_CODE VARCHAR(255),
    PNAME VARCHAR(255) NOT NULL,
    PDESCRIPTION VARCHAR(255) NOT NULL,
    PUNIT VARCHAR(255) NOT NULL,
    PCATEGORY VARCHAR(255) NOT NULL,
    QTY INTEGER NOT NULL,
    PPI INTEGER NOT NULL,
    TC INTEGER NOT NULL,
    ISAPPROVED BOOLEAN NOT NULL,
    EXP_DATE DATE NOT NULL,
    ADDED_ON DATE NOT NULL
);

CREATE TABLE DAMAGED(
    IID VARCHAR(20) NOT NULL PRIMARY KEY,
    VENDOR_CODE VARCHAR(255) NOT NULL,
    PNAME VARCHAR(255) NOT NULL,
    DAMAGE_TYPE VARCHAR(255) NOT NULL,
    QTY INTEGER NOT NULL,
    PPI INTEGER NOT NULL,
    TC INTEGER NOT NULL,
    EXP_DATE DATE NOT NULL
);

CREATE TABLE ORDER_(
    IID VARCHAR(200) NOT NULL PRIMARY KEY,
    WAREHOUSE_NAME VARCHAR(255) NOT NULL,
    PNAME VARCHAR(255) NOT NULL,
    QTY INTEGER NOT NULL,
    PPI INTEGER NOT NULL,
    TC INTEGER NOT NULL,
    SOLD_ON DATE NOT NULL
);

CREATE TABLE ORDERS(
    OID VARCHAR(255) NOT NULL PRIMARY KEY,
    WAREHOUSE_NAME VARCHAR(255) NOT NULL,
    PNAME VARCHAR(255) NOT NULL,
    TC INTEGER NOT NULL,
    SOLD_ON DATE NOT NULL,
    ISACTIVE BOOLEAN NOT NULL
);


